INFO:aiogram:Bot: PolundraHack [@Elbrus5Bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:786941244 запустил бота в Wed Sep 29 10:11:10 2021
INFO:root:Нам написал Илья Рыжков, его id = 786941244
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:406> exception=TypeError('sequence item 0: expected str instance, Series found')>
Traceback (most recent call last):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 414, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\bot_test.py", line 78, in echo_message
    await bot.send_message(similar_artist(txt, dict_of_artist_similary, text_dict))
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\model_test.py", line 17, in similar_artist
    return final_df(artist_name, dict_of_artist_similary, text_dict)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\api\musicmatcher.py", line 69, in final_df
    return (',\n'.join([df[artist_name].sort_values(ascending=False).head(6)[1:]]))
TypeError: sequence item 0: expected str instance, Series found
INFO:root:Нам написал Илья Рыжков, его id = 786941244
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:406> exception=KeyError("'Eminem'")>
Traceback (most recent call last):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: "'Eminem'"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 414, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\bot_test.py", line 78, in echo_message
    await bot.send_message(similar_artist(txt, dict_of_artist_similary, text_dict))
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\model_test.py", line 17, in similar_artist
    return final_df(artist_name, dict_of_artist_similary, text_dict)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\api\musicmatcher.py", line 69, in final_df
    return (',\n'.join([df[artist_name].sort_values(ascending=False).head(6)[1:]]))
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: "'Eminem'"
INFO:root:Нам написал Илья Рыжков, его id = 786941244
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:406> exception=TypeError('sequence item 0: expected str instance, Series found')>
Traceback (most recent call last):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 414, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\bot_test.py", line 78, in echo_message
    await bot.send_message(similar_artist(txt, dict_of_artist_similary, text_dict))
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\model_test.py", line 17, in similar_artist
    return final_df(artist_name, dict_of_artist_similary, text_dict)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\api\musicmatcher.py", line 69, in final_df
    return (',\n'.join([df[artist_name].sort_values(ascending=False).head(6)[1:]]))
TypeError: sequence item 0: expected str instance, Series found
INFO:aiogram:Bot: PolundraHack [@Elbrus5Bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:786941244 запустил бота в Wed Sep 29 10:22:15 2021
INFO:root:Нам написал Илья Рыжков, его id = 786941244
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:406> exception=TypeError('sequence item 0: expected str instance, Index found')>
Traceback (most recent call last):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 414, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\bot_test.py", line 78, in echo_message
    await bot.send_message(similar_artist(txt, dict_of_artist_similary, text_dict))
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\model_test.py", line 17, in similar_artist
    return final_df(artist_name, dict_of_artist_similary, text_dict)
  File "C:\Users\ryzhk\OneDrive\Документы\GitHub\ds_bootcamp\Bot_PolundraHack\pythonProject1\api\musicmatcher.py", line 69, in final_df
    return (',\n'.join([df[artist_name].sort_values(ascending=False).index[1:6]]))
TypeError: sequence item 0: expected str instance, Index found
